# Generated by Django 5.0.6 on 2024-06-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_alter_events_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrolls',
            name='income_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
